### ISSUE TITLE
Configuring MiniBlog as Virtual Application

### ISSUE THREAD

**Issue by edrohler** [madskristensen/MiniBlog#190]
I am using VS2015 with a base ASP.NET Website at www and would like it to be www.domain.com/blog. I copied the mini blog application to a "blog" subfolder, set it as a virtual directory in applicationhosting.config but keep receiving errors.

Is the documentation out of date for the Virtual Application section?
Do I need to make any changes to the root level web.config, if so, what?
Also, I am using IIS Express I hope to deploy it to Azure as a single web application if that is possible.

**Comment by RandomlyKnighted** [comment]
To my knowledge it's up to date. Did you follow the instructions in the README for virtual applications? It has some tweaks that you need to make in the web.config in order to point it to the blog subfolder.

**Comment by edrohler** [comment]
I did make the changes outlined in the README.md to the blog application web.config but I think I am missing the root level web.config changes. I have 2 web.configs one for the root level site and one for the MiniBlog application. Is that incorrect?

**Comment by edrohler** [comment]
Awesome! Thank you. You should be able to install VS2013 and VS2015 SxS now that 2015 is in RC..

**Comment by RandomlyKnighted** [comment]
@edrohler When creating up your original project, what kind of ASP.NET application did you create? (i.e. ASP.NET 5 Empty, Web API, Web Site, etc.) I want to make sure I try to duplicate your settings as much as possible while testing this.

**Comment by edrohler** [comment]
@RandomlyKnighted I just set up an empty asp.net website. File->New Website->Empty ASP.NET Website. Then added a folder for blog and copied the contents of the Website folder from the repo into the blog folder. The root level only had index.cshtml and a web.config.

**Comment by RandomlyKnighted** [comment]
@edrohler I just wanted to let you know that I am still trying to duplicate your project. I'm working at the moment on some issues I encountered with the NuGet packages (having to reinstall them).

**Comment by edrohler** [comment]
@RandomlyKnighted I think that is from an extension..Not sure though. I was able to build it as the top-level site. VS just downloaded the Nuget Packages on build.

**Comment by bilalashraf1** [comment]
I have deployed the blog on top of my mvc4 website and I am facing similar issues.


I am getting 404 on Admin functions. I cant login , create new post or update exiting post. The public pages works fine.




Wesbite: www.mysite.com - main mv4 website
Blog: www.mysite.com/blog - virtual app under my website which points to blog folder under root of my website. Blog folder contains the source and with the below web.config changes 

  <add key="blog:path" value="blog"/>

<handlers>
    <remove name="CommentHandler"/>
    <add name="CommentHandler" verb="*" type="CommentHandler" path="/blog/comment.ashx"/>
    <remove name="PostHandler"/>
    <add name="PostHandler" verb="POST" type="PostHandler" path="/blog/post.ashx"/>
    <remove name="MetaWebLogHandler"/>
    <add name="MetaWebLogHandler" verb="POST,GET" type="MetaWeblogHandler" path="/blog/metaweblog"/>
    <remove name="FeedHandler"/>
    <add name="FeedHandler" verb="GET" type="FeedHandler" path="/blog/feed/*"/>
    <remove name="CssHandler"/>
    <add name="CssHandler" verb="GET" type="MinifyHandler" path="/blog*.css"/>
    <remove name="JsHandler"/>
    <add name="JsHandler" verb="GET" type="MinifyHandler" path="/blog*.js"/>
</handlers>

<httpErrors>
    <remove statusCode="404"/>
    <error statusCode="404" responseMode="ExecuteURL" path="/blog/404.cshtml"/>
</httpErrors>

**Comment by RandomlyKnighted** [comment]
@edrohler were you able to figure out the cause of your issue? Once I got the project to run, I continued to get errors like you were.

**Comment by edrohler** [comment]
Nah, I still get the errors. I think I am going to try and use Orchard..

**Comment by RandomlyKnighted** [comment]
@madskristensen do you have any suggestions?

**Comment by programcsharp** [comment]
I ran into some similar issues when setting this up, but finally got it
working. Unfortunately I can't remember exactly what the issues were.

Here's how I have it set up:
 - root www.bla.com is a site in IIS
 - blog folder underneath www.bla.com is an application in IIS
 - made the handler tweaks recommended in README.md

Have you tried making some test .cshtml and/or commenting out some of the
handlers to see if you can get at least something responding and then work
from there?

Also, do you have the IIS rewrite module installed? MiniBlog uses that to
handle the URL's. Also note that it has a rule by default that removes www
from the URL, so make sure you have a non www binding, not just a www
binding.
